apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: prom-pvc-claim

spec:
  storageClassName: manual
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi